flowchart LR
    N001["Valid"]
    N002["Invalid"]
    N003["Unique"]
    N004["Shared"]
    N005["UC"]
    N006["SC"]
    N007["Clean"]
    N008["UCE"]
    N009["I"]
    N010["UD"]
    N011["SD"]
    N012["Dirty"]
    N013["UDP"]
    N001 --- N003
    N004 --- N001
