flowchart LR
    N001["Note"]
    N002["B10.7.1"]
    N003["Introduction"]
    N004["RME-DA and RME-CDA enables the secure assignment of assignable device interfaces."]
    N005["Device<br/>Accelerator"]
    N006["Device"]
    N007["Host"]
    N008["Accelerator"]
    N009["DCM"]
    N010["HCM"]
    N006 --- N008
    N008 --- N006
