flowchart LR
    N001["Local socket"]
    N002["Local die"]
    N003["Remote die or chiplet"]
    N004["Cluster 1"]
    N005["Cluster 0"]
    N006["Cluster 0"]
    N007["Processor X"]
    N008["Processor 0"]
    N009["Processor 1"]
    N010["Processor 0"]
    N011["Processor 1"]
    N012["Processor X"]
    N013["Processor 0"]
    N014["Processor 1"]
    N015["A"]
    N016["B"]
    N017["Cache"]
    N018["Cache"]
    N019["Cache"]
    N020["Cache"]
    N021["Cache"]
    N022["Cache"]
    N023["Cache"]
    N024["Cache"]
    N025["Cache"]
    N026["Cache"]
    N027["Cache"]
    N028["Interconnect"]
    N029["Cache"]
    N030["C"]
    N031["Interconnect"]
    N032["Cache"]
    N033["CXL"]
    N034["CXL"]
    N035["High BW"]
    N036["High BW"]
    N037["DDR"]
    N038["DDR"]
    N039["Memory"]
    N040["Memory"]
    N041["Remote socket<br/>Remote socket"]
    N042["Remote socket"]
    N043["Cluster 1"]
    N044["Cluster 0"]
    N045["Cluster 0"]
    N046["Processor X"]
    N047["Processor X"]
    N048["Processor 0"]
    N049["Processor 1"]
    N050["Processor 0"]
    N051["Processor 1"]
    N052["Processor 0"]
    N053["Processor 1"]
    N054["D"]
    N055["Cache"]
    N056["Cache"]
    N057["Cache"]
    N058["Cache"]
    N059["Cache"]
    N060["Cache"]
    N061["Cache"]
    N062["Cache"]
    N063["Cache"]
    N064["Cache"]
    N065["Cache"]
    N066["Interconnect"]
    N067["Cache"]
    N068["Interconnect"]
    N069["Cache"]
    N070["CXL"]
    N071["E"]
    N072["CXL"]
    N073["High BW"]
    N074["High BW"]
    N075["DDR"]
    N076["DDR"]
    N077["Memory"]
    N078["Memory"]
    N017 --- N029
    N022 --- N032
    N055 --- N067
    N056 --- N069
