flowchart LR
    N001["6"]
    N002["5"]
    N003["4"]
    N004["3"]
    N005["1"]
    N006["0"]
    N007["Unique"]
    N008["CacheLevel"]
    N009["Replacement"]
    N010["UnusedPrefetch"]
    N002 --- N007
