flowchart LR
    N001["ICN"]
    N002["RN-I"]
    N003["TXREQ"]
    N004["REQ"]
    N005["RXREQ"]
    N006["RXRSP"]
    N007["RSP"]
    N008["TXRSP"]
    N009["RXDAT"]
    N010["DAT"]
    N011["TXDAT"]
    N012["TXRSP"]
    N013["RSP"]
    N014["RXRSP"]
    N015["TXDAT"]
    N016["DAT"]
    N017["RXDAT"]
    N003 --> N005
    N008 --> N006
    N011 --> N009
    N012 --> N014
    N015 --> N017
