flowchart LR
    N001["RN-F"]
    N002["TXREQ0"]
    N003["REQ0"]
    N004["TXREQ1"]
    N005["REQ1"]
    N006["RXRSP0"]
    N007["RSP0"]
    N008["Single interface"]
    N009["RXRSP1"]
    N010["RSP1"]
    N011["RXDAT0"]
    N012["DAT0"]
    N013["RXDAT1"]
    N014["DAT1"]
    N015["RXSNP0"]
    N016["SNP0"]
    N017["TXRSP0"]
    N018["RSP0"]
    N019["TXDAT0"]
    N020["DAT0"]
    N021["TXDAT1"]
    N022["DAT1"]
    N002 --> N003
    N004 --> N005
