flowchart LR
    N001["RN-F"]
    N002["Port"]
    N003["TXSACTIVE<br/>RXSACTIVE"]
    N004["Outbound link"]
    N005["TXLINKACTIVEREQ"]
    N006["TXLINKACTIVEACK"]
    N007["REQ channel"]
    N008["TXREQFLITPEND"]
    N009["TXREQFLITV"]
    N010["TXREQFLIT"]
    N011["TXREQFLIPTRP"]
    N012["TXREQSHAREDCRD<br/>TXREQLCRDV"]
    N013["TXREQLCRDSHV"]
    N014["TX"]
    N015["RSP channel"]
    N016["TXRSPFLITPEND"]
    N017["TXRSPFLITV"]
    N018["TXRSPFLIT"]
    N019["TXRSPLCRDV"]
    N020["DAT channel"]
    N021["TXDATFLITPEND"]
    N022["TXDATFLITV"]
    N023["TXDATFLIT"]
    N024["TXDATLCRDV"]
    N025["Inbound link"]
    N026["RXLINKACTIVEREQ"]
    N027["RXLINKACTIVEACK"]
    N028["RSP channel"]
    N029["RXRSPFLITPEND"]
    N030["RXRSPFLITV"]
    N031["RXRSPFLIT"]
    N032["RXRSPLCRDV"]
    N033["DAT channel"]
    N034["RXDATFLITPEND"]
    N035["RXDATFLITV"]
    N036["RX"]
    N037["RXDATFLIT"]
    N038["RXDATLCRDV"]
    N039["SNP channel"]
    N040["RXSNPFLITPEND"]
    N041["RXSNPFLITV"]
    N042["RXSNPFLIT"]
    N043["RXSNPFLIPTRP"]
    N044["RXSNPSHAREDCRD"]
    N045["RXSNPLCRDV"]
    N046["RXSNPLCRDSHV"]
    N012 --- N013
    N045 --> N044
