flowchart LR
    N001["RN-F"]
    N002["TXREQ"]
    N003["REQ"]
    N004["RXRSP"]
    N005["RSP"]
    N006["Interface 1"]
    N007["RXDAT"]
    N008["DAT"]
    N009["RXSNP"]
    N010["SNP"]
    N011["TXRSP"]
    N012["RSP"]
    N013["TXDAT"]
    N014["DAT"]
    N015["TXREQ"]
    N016["REQ"]
    N017["RXRSP"]
    N018["RSP"]
    N019["Interface 2"]
    N020["RXDAT"]
    N021["DAT"]
    N022["RXSNP"]
    N023["SNP"]
    N024["TXRSP"]
    N025["RSP"]
    N026["TXDAT"]
    N027["DAT"]
