flowchart LR
    N001["Transmitter"]
    N002["Receiver"]
    N003["REQFLITPEND"]
    N004["TXREQFLITPEND"]
    N005["RXREQFLITPEND"]
    N006["REQFLITV"]
    N007["TXREQFLITV"]
    N008["RXREQFLITV"]
    N009["REQFLIT[FLIT_WIDTH-1:0]"]
    N010["TXREQFLIT"]
    N011["RXREQFLIT"]
    N012["REQFLITRP[clog 2 (Num_RP_REQ)-1:0]"]
    N013["TXREQFLITRP"]
    N014["RXREQFLITRP"]
    N015["REQSHAREDCRD"]
    N016["TXREQSHAREDCRD"]
    N017["RXREQSHAREDCRD"]
    N018["RXREQLCRDV"]
    N019["TXREQLCRDV"]
    N020["REQLCRDV[Num_RP_REQ-1:0]"]
    N021["REQLCRDSHV"]
    N022["TXREQLCRDSHV"]
    N023["RXREQLCRDSHV"]
    N004 --> N005
    N007 --> N008
    N010 --> N011
    N013 --> N014
    N016 --> N017
    N018 --> N019
    N023 --> N022
