flowchart LR
    N001["Node 1"]
    N002["Node 2"]
    N003["Node 3"]
    N004["Rx Tx"]
    N005["Rx Tx"]
    N006["Rx Tx"]
    N007["Tx Rx"]
    N008["Tx Rx"]
    N009["Tx Rx"]
    N010["Interconnect"]
    N011["Links"]
    N012["Tx Rx"]
    N013["Tx Rx"]
    N014["Tx Rx"]
    N015["Rx Tx"]
    N016["Rx Tx"]
    N017["Rx Tx"]
    N018["Node 4"]
    N019["Node 5"]
    N020["Node 6"]
    N011 --> N006
    N011 --> N014
