flowchart LR
    N001["Node"]
    N002["Interconnect"]
    N003["Transmitter"]
    N004["Receiver"]
    N005["Link 1"]
    N006["(TX)"]
    N007["(RX)"]
    N008["Receiver"]
    N009["Transmitter"]
    N010["Link 2"]
    N011["(RX)"]
    N012["(TX)"]
