flowchart LR
    N001["0"]
    N002["1"]
    N003["2"]
    N004["3"]
    N005["4"]
    N006["5"]
    N007["6"]
    N008["7"]
    N009["8"]
    N010["9"]
    N011["10"]
    N012["CLK"]
    N013["LCRDV[0]"]
    N014["LCRDV[1]"]
    N015["LCRDV[2]"]
    N016["LCRDSHV"]
    N017["FLITPEND"]
    N018["FLITV"]
    N019["SHAREDCRD"]
    N020["FLITRP[1:0]"]
    N021["RP1"]
    N022["RP2 RP2"]
    N023["RP0"]
    N024["FLIT[FLIT_WIDTH-1:0]"]
    N025["flit"]
    N026["flit"]
    N027["flit"]
    N028["flit"]
    N029["Dedicated RP0 credit count"]
    N030["0"]
    N031["0"]
    N032["1"]
    N033["1"]
    N034["1"]
    N035["1"]
    N036["1"]
    N037["1"]
    N038["1"]
    N039["0"]
    N040["1"]
    N041["Dedicated RP1 credit count"]
    N042["0"]
    N043["0"]
    N044["1"]
    N045["0"]
    N046["1"]
    N047["1"]
    N048["1"]
    N049["1"]
    N050["1"]
    N051["1"]
    N052["1"]
    N053["Dedicated RP2 credit count"]
    N054["0"]
    N055["0"]
    N056["1"]
    N057["1"]
    N058["1"]
    N059["1"]
    N060["0"]
    N061["0"]
    N062["1"]
    N063["1"]
    N064["1"]
    N065["Shared credit count"]
    N066["0"]
    N067["0"]
    N068["1"]
    N069["1"]
    N070["1"]
    N071["1"]
    N072["1"]
    N073["0"]
    N074["1"]
    N075["1"]
    N076["2"]
