flowchart LR
    N001["B14.5.1.3"]
    N002["Multiple channels in the same direction"]
    N003["LINKACTIVEREQ"]
    N004["LINKACTIVEACK"]
    N005["Payload flit"]
    N006["Credit"]
    N007["Transmitter"]
    N008["Receiver"]
    N009["Payload flit"]
    N010["Credit"]
    N011["Payload flit"]
    N012["Credit"]
