flowchart LR
    N001["Note"]
    N002["An L-Credit cannot be used in the same cycle as being received."]
    N003["Figure B14.1 shows an example use of a channel with no Resource Planes."]
    N004["0"]
    N005["1"]
    N006["2"]
    N007["3"]
    N008["4"]
    N009["5"]
    N010["6"]
    N011["7"]
    N012["8"]
    N013["9"]
    N014["CLK"]
    N015["LCRDV"]
    N016["FLITPEND"]
    N017["FLITV"]
    N018["Credit count"]
    N019["0"]
    N020["0"]
    N021["1"]
    N022["0"]
    N023["1"]
    N024["2"]
    N025["2"]
    N026["1"]
    N027["2"]
    N028["1"]
    N003 --- N001
