flowchart LR
    N001["0"]
    N002["1"]
    N003["2"]
    N004["3"]
    N005["4"]
    N006["5"]
    N007["6"]
    N008["7"]
    N009["CLK"]
    N010["FLITPEND"]
    N011["FLITV"]
    N012["FLIT"]
    N013["flit"]
    N014["flit"]
