flowchart LR
    N001["Table B16.54 – Continued from previous page"]
    N002["BROADCASTLIMELISION"]
    N003["Description"]
    N004["Present"]
    N005["When BROADCASTLIMELISION is 1"]
    N006["An example system with different Limited Data Elision capabilities is shown in Figure B16.1 ."]
    N007["RN0"]
    N008["RN1"]
    N009["BROADCASTLIMELISION"]
    N010["BROADCASTLIMELISION"]
    N011["Limited"]
    N012["Limited"]
    N013["BROADCASTLIMELISION"]
    N014["HN"]
    N015["Limited"]
    N016["SN0"]
    N017["SN1"]
    N018["BROADCASTLIMELISION"]
    N019["Limited"]
    N002 --- N001
