sequenceDiagram
    participant Requester as Requester
    participant Home as Home
    participant Subordinate as Subordinate
    participant Snoopee as Snoopee
    Requester->>Home: ReadNoSnp, ReadOnce,<br/>ReadOnceCleanInvalid, ReadOnceMakeInvalid
    Home->>Requester: [Order != 00]<br/>ReadReceipt
    Home->>Requester: CompData
    Requester->>Snoopee: [2. Separate Data and Response from Home]<br/>RespSepData
    Home->>Requester: [2. Separate Data and Response from Home]<br/>RespSepData
    Home->>Requester: DataSepResp
    Requester->>Snoopee: DataSepResp
    Home->>Requester: 
    Home->>Subordinate: ReadNoSnp
    Subordinate->>Home: [Order != 00]<br/>ReadReceipt
    Subordinate->>Requester: CompData
    Requester->>Snoopee: [4. Response from Home, Data from Subordinate]<br/>RespSepData
    Home->>Requester: [4. Response from Home, Data from Subordinate]<br/>RespSepData
    Home->>Subordinate: ReadNoSnpSep
    Subordinate->>Home: [Order != 00]<br/>ReadReceipt
    Subordinate->>Requester: DataSepResp
    Requester->>Snoopee: DataSepResp
    Home->>Requester: Snp*Fwd
    Home->>Snoopee: Snp*Fwd
    Snoopee->>Requester: [5a. With response to Home]<br/>CompData
    Snoopee->>Home: SnpRespFwded
    Requester->>Snoopee: [5b. With data to Home]<br/>CompData
    Snoopee->>Requester: [5b. With data to Home]<br/>CompData
    Snoopee->>Home: SnpRespDataFwded
    Requester->>Snoopee: [5c. Failed, must use alternative]
    Snoopee->>Home: SnpResp
    Requester->>Snoopee: [5d. Failed, must use alternative]
    Snoopee->>Home: SnpRespData, SnpRespDataPtl
    Requester->>Home: [ExpCompAck == 1]<br/>CompAck