sequenceDiagram
    participant Home as Home
    participant Snoopee as Snoopee
    Home->>Snoopee: Snp*, Snp*Fwd
    Snoopee->>Home: [2. Data to home]
    Home->>Snoopee: [2. Data to home]
    Snoopee->>Home: SnpRespData, SnpRespDataPtl
