flowchart LR
    N001["RN"]
    N002["RN-F"]
    N003["ICN"]
    N004["*"]
    N005["(SrcID)"]
    N006["SrcID"]
    N007["*"]
    N008["TgtID"]
    N009["R"]
    N010["(TgtID)"]
    N011["*"]
    N012["TxnID"]
    N013["TxnID"]
    N014["Snp[*]Stash"]
    N015["*"]
    N016["(SrcID)"]
    N017["SrcID"]
    N018["StashLPID"]
    N019["StashLPID"]
    N020["*"]
    N021["TxnID"]
    N022["TxnID"]
    N023["StashOnce or<br/>StashOnceSep"]
    N024["*"]
    N025["StashNID"]
    N026["StashNID"]
    N027["*"]
    N028["StashLPID"]
    N029["StashLPID"]
    N030["RN-F Node ID"]
    N031["*"]
    N032["StashGroupID"]
    N033["StashGroupID"]
    N034["same as<br/>StashNID"]
    N035["TgtID"]
    N036["Comp"]
    N037["TxnID"]
    N038["SrcID"]
    N039["(SrcID)"]
    N040["(TgtID)"]
    N041["TgtID"]
    N042["SnpResp_I_Read"]
    N043["TxnID"]
    N044["TxnID"]
    N045["For StashOnceSep"]
    N046["DBID"]
    N047["DBID"]
    N048["*"]
    N049["TgtID"]
    N050["StashDone"]
    N051["TxnID"]
    N052["(SrcID)"]
    N053["SrcID"]
    N054["StashGroupID"]
    N055["TgtID"]
    N056["(TgtID)"]
    N057["TxnID"]
    N058["TxnID"]
    N059["Alternative combined"]
    N060["CompData"]
    N061["*"]
    N062["DBID"]
    N063["DBID"]
    N064["Comp and"]
    N065["*"]
    N066["(HomeNID)"]
    N067["HomeNID"]
    N068["StashDone"]
    N069["TgtID"]
    N070["TgtID"]
    N071["CompStashDone"]
    N072["TxnID"]
    N073["CompAck"]
    N074["(SrcID)"]
    N075["StashGroupID"]
    N076["TxnID<br/>DBID"]
