flowchart LR
    N001["Comp and Data"]
    N002["7 6 5 4 3 2 1 0"]
    N003["value size"]
    N004["S"]
    N005["C"]
    N006["Example 1: Addr = 0x2"]
    N007["1 byte each"]
    N008["7 6 5 4 3 2 1 0"]
    N009["C"]
    N010["S"]
    N011["Example 2: Addr = 0x5"]
    N012["7 6 5 4 3 2 1 0"]
    N013["C"]
    N014["C"]
    N015["S"]
    N016["S"]
    N017["Example 3: Addr = 0x2"]
    N018["2 bytes each"]
    N019["7 6 5 4 3 2 1 0"]
    N020["S"]
    N021["S"]
    N022["C"]
    N023["C"]
    N024["Example 4: Addr = 0x4"]
    N025["Only 8 bytes of the 16-byte data packet are shown."]
