flowchart LR
    N001["Note"]
    N002["Examples where it is not possible to elide any packets from a data message are also included in Figure<br/>B2.40 ."]
    N003["Original"]
    N004["With Limited Data Elision"]
    N005["Packet 1"]
    N006["Packet 0"]
    N007["Packet 1"]
    N008["Packet 0"]
    N009["Packet 3"]
    N010["Packet 2"]
    N011["Packet 3"]
    N012["Packet 2"]
    N013["DataID=01"]
    N014["DataID=00"]
    N015["DataID=01"]
    N016["DataID=00"]
    N017["DataID=11"]
    N018["DataID=10"]
    N019["DataID=11"]
    N020["DataID=10"]
    N021["0"]
    N022["0"]
    N023["Not sent"]
    N024["Not sent"]
    N025["0"]
    N026["0"]
    N027["0"]
    N028["Not sent"]
    N029["NumDat=3<br/>Replicate=0 or 1<br/>A"]
    N030["A"]
    N031["A"]
    N032["A"]
    N033["A"]
    N034["Not sent"]
    N035["Not sent"]
    N036["Not sent"]
    N037["NumDat=3<br/>Replicate=1<br/>A"]
    N038["0"]
    N039["0"]
    N040["0"]
    N041["A"]
    N042["Not sent"]
    N043["Not sent"]
    N044["Not sent"]
    N045["NumDat=3<br/>Replicate=0"]
    N046["A"]
    N047["0"]
    N048["A"]
    N049["0"]
    N050["0"]
    N051["Not sent"]
    N052["NumDat=3"]
    N053["Not sent"]
    N054["Not sent"]
    N055["Replicate=0<br/>C"]
    N056["B"]
    N057["A"]
    N058["C"]
    N059["C"]
    N060["B"]
    N061["A"]
    N062["Not sent"]
    N063["NumDat=1"]
    N064["NumDat=0"]
    N065["NumDat=0"]
    N066["Replicate=0 a"]
    N067["Replicate=0 a"]
    N068["Replicate=1"]
    N069["A"]
    N070["A"]
    N071["A"]
    N072["A"]
    N073["0"]
    N074["0"]
    N075["NumDat=2"]
    N076["NumDat=0"]
    N077["Not sent"]
    N078["Not sent"]
    N079["Replicate=0 a"]
    N080["Replicate=0"]
    N081["A"]
    N082["0"]
    N083["A"]
    N084["Not sent"]
    N085["NumDat=1<br/>Replicate=0"]
    N086["A"]
    N087["0"]
    N088["A"]
    N089["0"]
    N090["NumDat=0"]
    N091["NumDat=0"]
    N092["Replicate=0 a"]
    N093["Replicate=0 a"]
    N094["A"]
    N095["0"]
    N096["A"]
    N097["Not sent"]
    N098["NumDat=1<br/>Replicate=0"]
    N099["A"]
    N100["0"]
    N101["A"]
    N102["0"]
    N103["NumDat=0"]
    N104["NumDat=0"]
    N105["Replicate=0 a<br/>a Inapplicable and must be zero."]
    N106["Replicate=0 a"]
