flowchart LR
    N001["Device Read transaction<br/>Size = 0b110 (64-bytes)"]
    N002["Data size boundary"]
    N003["Data size boundary"]
    N004["Addr = 0x0058"]
    N005["0x8F"]
    N006["0x80 0x7F"]
    N007["0x70 0x6F"]
    N008["0x60 0x5F"]
    N009["0x58 0x57 0x50 0x4F"]
    N010["0x40 0x3F"]
    N011["0x30 0x2F"]
    N012["0x20"]
    N013["Packet 2"]
    N014["Packet 1"]
    N015["Packet 0"]
    N016["Packet 3"]
    N017["DataID = 0x3"]
    N018["DataID = 0x2"]
    N019["DataID = 0x1"]
    N020["DataID = 0x0"]
    N021["CCID = 0x1"]
    N022["CCID = 0x1"]
    N023["CCID = 0x1"]
    N024["CCID = 0x1"]
    N004 --> N009
