flowchart LR
    N001["Normal Memory Read transaction<br/>Size = 0b110 (64-bytes)"]
    N002["Data size boundary"]
    N003["Data size boundary"]
    N004["Addr = 0x0068"]
    N005["0x8F"]
    N006["0x80 0x7F"]
    N007["0x70"]
    N008["0x6F"]
    N009["0x68"]
    N010["0x67"]
    N011["0x60"]
    N012["0x5F"]
    N013["0x50 0x4F"]
    N014["0x40"]
    N015["0x3F"]
    N016["0x30"]
    N017["0x2F"]
    N018["0x20"]
    N019["Packet 1"]
    N020["Packet 0"]
    N021["Packet 3"]
    N022["Packet 2"]
    N023["DataID = 0x3"]
    N024["DataID = 0x1"]
    N025["DataID = 0x0"]
    N026["DataID = 0x2"]
    N027["CCID = 0x2"]
    N028["CCID = 0x2"]
    N029["CCID = 0x2"]
    N030["CCID = 0x2"]
    N004 --> N009
