flowchart LR
    N001["Device Write transaction<br/>Size = 0b110 (64-bytes)"]
    N002["Data size boundary"]
    N003["Addr = 0x0068"]
    N004["Data size boundary"]
    N005["24-bytes written"]
    N006["0x8F"]
    N007["0x80 0x7F"]
    N008["0x70 0x6F"]
    N009["0x68 0x67"]
    N010["0x60 0x5F"]
    N011["0x50 0x4F"]
    N012["0x40 0x3F"]
    N013["0x30 0x2F"]
    N014["0x20"]
    N015["Packet 1"]
    N016["Packet 0"]
    N017["Packet 3"]
    N018["Packet 2"]
    N019["DataID = 0x3"]
    N020["DataID = 0x2"]
    N021["DataID = 0x1"]
    N022["DataID = 0x0"]
    N023["CCID = 0x2"]
    N024["CCID = 0x2"]
    N025["CCID = 0x2"]
    N026["CCID = 0x2"]
    N027["BE = 0xFFFF"]
    N028["BE = 0xFF00"]
    N029["BE = 0x0000"]
    N030["BE = 0x0000"]
    N005 --> N009
