sequenceDiagram
    participant RN_F as RN-F
    participant HN_F as HN-F
    participant SN_F as SN-F
    RN_F->>HN_F: ReadNoSnp<br/>(ExpCompAck = 1)<br/>(Order[1:0] = 0b00)
    HN_F->>SN_F: ReadNoSnpSep
    HN_F->>RN_F: RespSepData
    SN_F->>HN_F: ReadReceipt
    RN_F->>HN_F: CompAck
    SN_F->>RN_F: DataSepResp
