sequenceDiagram
    participant RN_F0 as RN-F0
    participant RN_F1 as RN-F1
    participant RN_F2 as RN-F2
    participant HN_F as HN-F
    participant SN_F as SN-F
    RN_F1->>RN_F2: CleanUnique
    RN_F0->>HN_F: CleanUnique
    RN_F2->>RN_F1: CleanUnique
    RN_F2->>HN_F: SnpCleanInvalid
    HN_F->>RN_F1: SnpCleanInvalid
    HN_F->>RN_F2: SnpCleanInvalid
    RN_F1->>RN_F2: SnpCleanInvalid
    RN_F2->>RN_F1: SnpCleanInvalid
    RN_F1->>RN_F2: SnpRespData_I_PD
    RN_F2->>RN_F1: SnpRespData_I_PD
    RN_F1->>HN_F: SnpRespData_I_PD
    RN_F2->>HN_F: SnpResp_I
    RN_F2->>HN_F: SnpResp_I
    HN_F->>SN_F: WriteNoSnp
    HN_F->>RN_F2: SnpResp_I
    HN_F->>SN_F: WriteNoSnp
    SN_F->>HN_F: WriteNoSnp
    HN_F->>SN_F: CompDBIDResp
    SN_F->>HN_F: CompDBIDResp
    RN_F1->>RN_F2: Comp_UC
    HN_F->>RN_F0: Comp_UC
    RN_F2->>RN_F1: Comp_UC
    HN_F->>SN_F: NCBWrData
    HN_F->>SN_F: NCBWrData
    SN_F->>HN_F: NCBWrData
    RN_F1->>RN_F2: CompAck
    RN_F0->>HN_F: CompAck
    RN_F2->>RN_F1: CompAck
