sequenceDiagram
    participant RN_F0 as RN-F0
    participant RN_F1 as RN-F1
    participant RN_F2 as RN-F2
    participant HN_F as HN-F
    participant SN_F as SN-F
    RN_F1->>RN_F2: MakeUnique
    RN_F0->>HN_F: MakeUnique
    RN_F2->>RN_F1: MakeUnique
    RN_F2->>HN_F: SnpMakeInvalid
    HN_F->>RN_F1: SnpMakeInvalid
    HN_F->>RN_F2: SnpMakeInvalid
    RN_F1->>RN_F2: SnpMakeInvalid
    RN_F2->>RN_F1: SnpMakeInvalid
    RN_F1->>RN_F2: SnpResp_I
    RN_F2->>HN_F: SnpResp_I
    RN_F2->>HN_F: SnpResp_I
    RN_F2->>RN_F1: SnpResp_I
    HN_F->>RN_F2: SnpResp_I
    RN_F1->>HN_F: SnpResp_I
    RN_F1->>RN_F2: Comp_UC
    HN_F->>RN_F0: Comp_UC
    RN_F2->>RN_F1: Comp_UC
    RN_F1->>RN_F2: CompAck
    RN_F0->>HN_F: CompAck
    RN_F2->>RN_F1: CompAck
