sequenceDiagram
    participant RN_F0 as RN-F0
    participant RN_F1 as RN-F1
    participant RN_F2 as RN-F2
    participant HN_F as HN-F
    participant SN_F as SN-F
    RN_F2->>HN_F: Req1: ReadShared
    RN_F2->>HN_F: Req1: ReadShared
    HN_F->>RN_F2: Req1: ReadShared
    RN_F1->>RN_F2: Req2: ReadUnique
    HN_F->>SN_F: ReadNoSnp
    RN_F0->>HN_F: Req2: ReadUnique
    RN_F2->>RN_F1: Req2: ReadUnique
    HN_F->>SN_F: ReadNoSnp
    SN_F->>HN_F: ReadNoSnp
    SN_F->>HN_F: A
    HN_F->>RN_F0
    HN_F->>RN_F1: SnpShared
    RN_F1->>RN_F2: SnpShared
    RN_F0->>RN_F1: SnpShared
    RN_F2->>RN_F1: SnpShared
    RN_F1->>RN_F0: SnpShared
    RN_F0->>RN_F1: SnpResp_SC
    RN_F1->>RN_F2: SnpResp_I
    RN_F1->>RN_F0: SnpResp_SC
    RN_F2->>RN_F1: SnpResp_I
    RN_F1->>HN_F: SnpResp_I
    RN_F0->>HN_F
    HN_F->>SN_F: CompData_I
    SN_F->>HN_F: CompData_I
    RN_F2->>HN_F: CompData_SC
    HN_F->>RN_F2: CompData_SC
    HN_F->>RN_F2: CompData_SC
    RN_F2->>HN_F: CompAck
    RN_F2->>HN_F: CompAck
    HN_F->>RN_F2: CompAck
    SN_F->>HN_F: B
    HN_F->>SN_F: ReadNoSnp
    RN_F2->>HN_F: SnpUnique
    HN_F->>RN_F1: SnpUnique
    RN_F1->>RN_F2: SnpUnique
    HN_F->>RN_F2: SnpUnique
    SN_F->>HN_F: ReadNoSnp
    HN_F->>RN_F2: SnpUnique
    RN_F2->>RN_F1: SnpUnique
    RN_F1->>RN_F2: SnpResp_I
    RN_F2->>HN_F: SnpResp_I
    RN_F2->>RN_F1: SnpResp_I
    RN_F2->>HN_F: SnpResp_I
    RN_F1->>HN_F: SnpResp_I
    HN_F->>RN_F2: SnpResp_I
    HN_F->>SN_F: CompData_I
    SN_F->>HN_F: CompData_I
    RN_F1->>RN_F2: CompData_UC
    HN_F->>RN_F0: CompData_UC
    RN_F2->>RN_F1: CompData_UC
    RN_F1->>RN_F2: CompAck
    RN_F0->>HN_F: CompAck
    RN_F2->>RN_F1: CompAck
