flowchart LR
    N001["Long distance wiring<br/>and routing logic"]
    N002["Short distance wiring"]
    N003["Interconnect"]
    N004["AMBA"]
    N005["AMBA"]
    N006["Source"]
    N007["Destination"]
    N008["Parity"]
    N009["Parity"]
    N010["EDC code"]
    N011["Parity check and EDC"]
    N012["EDC check and Parity"]
    N013["Parity check"]
    N014["Parity generation"]
    N015["generation"]
    N016["generation"]
    N002 --> N004
